name: Deploy Vite Project

on:
  push:
    branches: ["master"] # На скриншоте видно, что у вас ветка master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 24 # Обновили до актуальной, чтобы убрать Warning
          cache: 'npm'

      - name: Install dependencies
        # Если у вас нет package-lock.json, npm ci не сработает, используем install
        run: npm install 

      - name: Build
        # Проверьте, что в package.json есть скрипт "build"
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
